---
- name: My primer playbook  
  hosts: web2
  become: true
  
  tasks:
    - name: Downgrade package
      ansible.builtin.yum:
        name: httpd=2.0
        state: present
        
    - name: Parchado Sistema RedHAt
      when: ansible_os_family == 'RedHat'
      notify:
        - restart server
      ansible.builtin.yum:
        name: '*'
        state: latest
    
  handlers:
    - name: restart server
      ansible.builtin.reboot:
        msg: "Rebooting server in 5 seconds"
